# #####################################################################
# Automatically generated by qmake (2.01a) Sun Nov 16 10:59:04 2008
# #####################################################################
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lexer.h \
    cpphtmlhighlighter.h
SOURCES += lexer.cpp \
    main.cpp \
    cpphtmlhighlighter.cpp
